# Generated by Django 2.2.6 on 2019-10-21 04:27

from django.db import migrations


def capitalize(apps, schema_editor):
    # get the Product mode/table
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        # change the product name or the column name
        # value before saved in the database
        product.name = product.name.capitalize()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]
    # specify a noop backward function, which will allow us
    # to go backward doing nothing instead of raising an exception

    operations = [
        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop,
        )
    ]
